### ISSUE TITLE
Figures are not displaying

### ISSUE THREAD

**Issue by ekarlowska** [primer-computational-mathematics/book#5]
Figures in multiple notebooks (not all) that are sourced from our repo are not displaying, despite using the same way to create them:
![image](https://user-images.githubusercontent.com/42903237/89311577-14af4980-d66e-11ea-92c0-1e55d2e25755.png)

For example, figure in Milankovitch cycles notebook displays fine, none displays in Camera calibration. The only differences are that the one in Milankovitch cycle is in the directory above current "../images", while the camera calibration figures are stored in the directory within the one where the notebook was created. Any thoughts on how to fix that?

**Comment by ddundo** [comment]
Also not displaying is my plotly figure which I saved as html here https://primer-computational-mathematics.github.io/book/mathematics/complex%20analysis/complex_functions.html#comp-exp

I am displaying it with IFrame

`from IPython.display import IFrame

IFrame("complexdata/exp_plotly.html", 800, 600)`

**Comment by ddundo** [comment]
I just realised that it was me who broke the hack the first time - sorry about that :) I will close this for now, but reopen if you see that it doesn't work somewhere @ekarlowska please
